name: Cloud Native Project
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      VERSION: ${{ github.sha }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_UN }}
          password: ${{ secrets.REGISTRY_PW }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: "sit722cnpart5"
          cluster-name: "sit722cnpart5"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Build and push Docker image
        run: |
          ./scripts/build-image.sh
          ./scripts/push-image.sh

      - name: Deploy to Kubernetes
        run: |
          ./scripts/deploy.sh
