name: Cloud Native Project
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
          REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
          REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          args: get pods
